// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EphemeralContext = { 
/**
 * Human-readable title for turn-scoped model-visible context.
 */
title: string, 
/**
 * Free-form text payload for turn-scoped model-visible context.
 */
text: string, };
